### ISSUE TITLE
[BUG] 堡里的种子标题似乎会被豆瓣信息占用

### ISSUE THREAD

**Issue by scatking** [techmovie/DouBan-Info-for-PT#1]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：Firefox 87.0 (64 位)  
* 浏览器版本：参照上文
* 所用用户脚本扩展名称：Tamper monkey
* 脚本版本：1.1.2

**问题描述**
安装脚本以后种子标题等信息被豆瓣卡片占用了:(

**复现步骤*
进入任意种子页面

**问题截图**
![](https://i.ibb.co/pvgz289/Snipaste-2021-04-28-17-05-56.png)
![](https://i.ibb.co/ByMcqJP/Snipaste-2021-04-28-17-06-19.png)

**Comment by scatking** [comment]
我又试了一下，似乎是因为我用的这个暗色主题的锅，改回原始主题就没问题了。
不知道有没有办法兼容这个暗色主题。

**Comment by techmovie** [comment]
主题名叫什么？

**Comment by scatking** [comment]
@techmovie 
/css/berlin.css?v=1.2
是这个主题
