### ISSUE TITLE
[BUG] 脚本好像在皮失效了

### ISSUE THREAD

**Issue by scatking** [techmovie/DouBan-Info-for-PT#2]
**为了更好地了解问题，请填写以下信息**
* 浏览器名称：Firefox  / edge
* 浏览器版本：88.0.1 (64 位)    / 90.0.818.56 (官方内部版本) (64 位)
* 所用用户脚本扩展名称：tamper monkey
* douban-info-for-pt版本：1.1.4

**问题描述**
在皮无法显示豆瓣信息 (自定义主题和默认主题都有试过，都不行)

**复现步骤**
随意进入一个有豆瓣词条的电影界面

**问题截图**
![](https://images2.imgbox.com/a8/b5/4Zg0v23d_o.png)

**Comment by techmovie** [comment]
![image](https://user-images.githubusercontent.com/59314774/117608855-78344d80-b191-11eb-826a-8b0cd0328ca9.png)
我这里貌似没问题，可能是接口抽疯吧。

**Comment by scatking** [comment]
![Snipaste_2021-05-10_13-57-10.png](https://i.loli.net/2021/05/10/8pRUwBvWJi9EASK.png)
是这个原因吗....

**Comment by techmovie** [comment]
@scatking 应该是的。

**Comment by scatking** [comment]
测试了一下，加入例外以后可以使用了...

**Comment by techmovie** [comment]
@scatking 这个接口是在在PTPP代码里看到的，具体谁在维护也不清楚。

**Comment by techmovie** [comment]
fixed in https://github.com/techmovie/DouBan-Info-for-PT/commit/379ef302322810005bbc2c4f4303e248cd0a81fb
