### ISSUE TITLE
[BUG] iptorrents 不能显示

### ISSUE THREAD

**Issue by plsharevme** [techmovie/DouBan-Info-for-PT#3]
iptorrents 不能显示 ，试了 https://avistaz.to/ 可以。

**Comment by techmovie** [comment]
@plsharevme 提供下种子id

**Comment by plsharevme** [comment]
![image](https://user-images.githubusercontent.com/64370408/132299300-fbae3eaf-6525-4a35-9ad7-be76f0bd19f1.png)

这个站可以， avistaz , iptorrent 全部不能。

https://www.iptorrents.com/torrent.php?id=4468496
https://www.iptorrents.com/torrent.php?id=4468409

进去页面了，脚本也没加载。

**Comment by techmovie** [comment]
应该是脚本没匹配到 `https://www.iptorrents.com` ，可以先用`https://iptorrents.com/`访问。
下版改掉。

**Comment by plsharevme** [comment]
okay 好的。
