### ISSUE TITLE
[BUG]识别影片豆瓣信息错误。

### ISSUE THREAD

**Issue by ningsibuqu** [techmovie/DouBan-Info-for-PT#4]
hdbits 种子 id 580366 《蜜桃成熟時》识别成
![image](https://user-images.githubusercontent.com/51028975/135057191-13150614-525b-44d1-a862-c5455f67f764.png)

**Comment by techmovie** [comment]
https://www.douban.com/search?cat=1002&q=tt0107565
![image](https://user-images.githubusercontent.com/59314774/135072042-c0f6cb35-d3d6-4564-ae2e-e960a63cec98.png)
没办法 豆瓣搜索就是这个结果..

**Comment by ningsibuqu** [comment]
> https://www.douban.com/search?cat=1002&q=tt0107565 ![image](https://user-images.githubusercontent.com/59314774/135072042-c0f6cb35-d3d6-4564-ae2e-e960a63cec98.png) 没办法 豆瓣搜索就是这个结果..

https://search.douban.com/movie/subject_search?search_text=tt0107565&cat=1002
这里搜正常。

**Comment by techmovie** [comment]
@ningsibuqu 这个搜索入口在哪里

**Comment by ningsibuqu** [comment]
> @ningsibuqu 这个搜索入口在哪里

https://movie.douban.com/
![image](https://user-images.githubusercontent.com/51028975/135072602-ebe78e34-ed39-4ae3-989c-1833218e7725.png)

**Comment by techmovie** [comment]
@ningsibuqu 我先换回官方的那个接口吧

**Comment by ningsibuqu** [comment]
> @ningsibuqu 我先换回官方的那个接口吧

https://github.com/JayXon/MoreMovieRatings
你看看这位大佬用的什么接口？他这个看豆瓣 imdb互看评分也挺好用的。

**Comment by techmovie** [comment]
@ningsibuqu 他用的就是这个 https://movie.douban.com/j/subject_suggest?q=${id}
