### ISSUE TITLE
[FEATURE] ptp requests 页面能不能也适配一下。

### ISSUE THREAD

**Issue by ningsibuqu** [techmovie/DouBan-Info-for-PT#5]
比如
requests.php?action=view&id=6750
一般都会有 imdb link
![image](https://user-images.githubusercontent.com/51028975/135484295-0552ec84-dad9-42ef-9a2a-606f13d44d6f.png)
和种子页面一样，在这旁边加上跳转豆瓣的超链接？
![image](https://user-images.githubusercontent.com/51028975/135484399-ba91f5ea-9d2b-436b-b583-9e1156e4a648.png)

**Comment by techmovie** [comment]
@ningsibuqu 可以
