### ISSUE TITLE
[BUG]这几天rarbg不起作用了https://rarbgprx.org/

### ISSUE THREAD

**Issue by fireflycao** [techmovie/DouBan-Info-for-PT#9]
[[**为了更好地了解问题，请填写以下信息**
* 浏览器名称：
* 浏览器版本：
* 所用用户脚本扩展名称：
* douban-info-for-pt版本：

**问题描述**

**复现步骤**

**问题截图**](https://rarbgprx.org/)
](https://rarbgprx.org/)

**Comment by techmovie** [comment]
我这里正常
